site_name: 創世記 - 重視家庭
site_url: https://biblestudy.elab.io
theme:
  name: 'material'


nav:
  - 創世記 - 重視家庭: index.md
  - 學生版: student.md
  - 教師版: teacher.md
  - 關於本教材: about.md 
  - 伊甸團契退修會2019: retreat2019.md 
